Repository NOW-SOPT-APP5-KakaoPay/KakaoPay-iOS, pull requests merged in 2024-05, with the labels that each got.

#2 [Setting] #1 - 초기 세팅
  KakaoPay-iOS/KakaoPay-iOS/Application/AppDelegate.swift
  KakaoPay-iOS/KakaoPay-iOS/Application/SceneDelegate.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Extension/NSObject+.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Extension/UIButton+.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Extension/UIImageView+.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Extension/UILabel+.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Extension/UIStackView+.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Extension/UITextField+.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Extension/UIView+.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Extension/UIViewController+.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Literals/FontLiterals.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Literals/StringLiterals.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Protocols/a.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Info.plist
  KakaoPay-iOS/KakaoPay-iOS/Network/Base/NetworkResult.swift
  KakaoPay-iOS/KakaoPay-iOS/Network/Home/DTO/GetHomeResponseDTO.swift
  KakaoPay-iOS/KakaoPay-iOS/Network/Home/Service/HomeAPIService.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Home/Cells/HomeCollectionViewCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Home/View/HomeView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Home/ViewController/HomeViewController.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/ViewController.swift
Labels: Setting⚙️, 가현💜

#4 [Setting] #3 - 초기 세팅(2)
  .gitignore
  KakaoPay-iOS/KakaoPay-iOS.xcodeproj/project.pbxproj
  KakaoPay-iOS/KakaoPay-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  KakaoPay-iOS/KakaoPay-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  KakaoPay-iOS/KakaoPay-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  KakaoPay-iOS/KakaoPay-iOS/Global/Literals/FontLiterals.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Black.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Blue.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Bluegray400.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Bluegray500.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Gray200.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Gray300.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Gray400.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Gray500.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Gray600.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_LightBlue.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Orange.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Pink.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Red.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_White.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_Yellow.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_YellowDark.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Color/Kakao_YellowLight.colorset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_kakaobank_logo.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_kakaobank_logo.imageset/img_kakaobank_logo.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_kakaobank_logo.imageset/img_kakaobank_logo@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_kakaobank_logo.imageset/img_kakaobank_logo@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_qrscan.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_qrscan.imageset/ic_qrscan.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_qrscan.imageset/ic_qrscan@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_qrscan.imageset/ic_qrscan@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_shinhan_logo.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_shinhan_logo.imageset/img_shinhan_logo.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_shinhan_logo.imageset/img_shinhan_logo@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_shinhan_logo.imageset/img_shinhan_logo@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_toss_logo.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_toss_logo.imageset/img_toss_logo.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_toss_logo.imageset/img_toss_logo@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_toss_logo.imageset/img_toss_logo@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Fonts/AppleSDGothicNeoR.ttf
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Fonts/AppleSDGothicNeoSB.ttf
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Info.plist
Labels: Setting⚙️, 가현💜

#9 [Feat] #7 - 송금 화면 구현
  KakaoPay-iOS/KakaoPay-iOS.xcodeproj/project.pbxproj
  KakaoPay-iOS/KakaoPay-iOS/Global/Literals/StringLiterals.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_add_button.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_add_button.imageset/btn_add.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_add_button.imageset/btn_add@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_add_button.imageset/btn_add@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_black_line.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_black_line.imageset/Rectangle 854.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_black_line.imageset/Rectangle 854@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_black_line.imageset/Rectangle 854@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_gray_line.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_gray_line.imageset/Line 1 (Stroke).png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_gray_line.imageset/Line 1 (Stroke)@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_gray_line.imageset/Line 1 (Stroke)@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_star_empty.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_star_empty.imageset/Vector (Stroke).png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_star_empty.imageset/Vector (Stroke)@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_star_empty.imageset/Vector (Stroke)@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_star_select.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_star_select.imageset/Vector (Stroke).png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_star_select.imageset/Vector (Stroke)@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Transfer_img/img_star_select.imageset/Vector (Stroke)@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/Cell/MyAccountHeaderView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/Cell/MyAccountTableViewCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/Cell/RecentHeaderView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/Cell/RecentTableViewCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/Model/TransferModel.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/View/TransferHeaderView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/View/TransferView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/ViewController/TransferViewController.swift
Labels: Feat🔥, 가현💜

#12 [Feat] #10 - 결제 화면 구현
  KakaoPay-iOS/KakaoPay-iOS.xcodeproj/project.pbxproj
  KakaoPay-iOS/KakaoPay-iOS/Global/Literals/StringLiterals.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_addcard.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_addcard.imageset/img_card_add.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_addcard.imageset/img_card_add@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_addcard.imageset/img_card_add@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_barcode.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_barcode.imageset/img_barcode.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_barcode.imageset/img_barcode@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_barcode.imageset/img_barcode@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_btn_more.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_btn_more.imageset/btn_more_ios.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_btn_more.imageset/btn_more_ios@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_btn_more.imageset/btn_more_ios@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_hanabank.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_hanabank.imageset/img_card_hana.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_hanabank.imageset/img_card_hana@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_hanabank.imageset/img_card_hana@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_kakaobank.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_kakaobank.imageset/img_card_kakaobank.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_kakaobank.imageset/img_card_kakaobank@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_kakaobank.imageset/img_card_kakaobank@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_kakaopay.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_kakaopay.imageset/img_card_kakaopay.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_kakaopay.imageset/img_card_kakaopay@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_kakaopay.imageset/img_card_kakaopay@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_qrcode.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_qrcode.imageset/img_qrcode.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_qrcode.imageset/img_qrcode@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_qrcode.imageset/img_qrcode@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_shinhan.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_shinhan.imageset/img_card_shinhan.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_shinhan.imageset/img_card_shinhan@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_shinhan.imageset/img_card_shinhan@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_tabbarPay.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_tabbarPay.imageset/tabbar_pay.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_tabbarPay.imageset/tabbar_pay@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Payment_img/img_tabbarPay.imageset/tabbar_pay@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Payment/Model/PaymentModel.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Payment/View/BarcodePaymentView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Payment/View/CustomDivideView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Payment/View/PaymentView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Payment/ViewController/PaymentViewController.swift
Labels: Feat🔥, 가현💜

#18 [Network] 자산 화면 API 연결
  KakaoPay-iOS/KakaoPay-iOS.xcodeproj/project.pbxproj
  KakaoPay-iOS/KakaoPay-iOS/Network/DTO/BookmarkResponseDTO.swift
  KakaoPay-iOS/KakaoPay-iOS/Network/DTO/GetHistoriesDTO.swift
  KakaoPay-iOS/KakaoPay-iOS/Network/Service/BookmarkService.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/Cell/RecentTableViewCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/View/TransferView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/ViewController/TransferViewController.swift
Labels: 혜린🩷, Network🛜

#21 [Fix] #20 - Trasfer View starButton 플로우 수정
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/Cell/RecentTableViewCell.swift
Labels: Fix🔨, 혜린🩷

#24 [Refactor] #23 - 코드 수정
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Home_img/img_Second.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Home_img/img_Second.imageset/img_second@1.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Home_img/img_Second.imageset/img_second@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/Image/Home_img/img_Second.imageset/img_second@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Payment/ViewController/PaymentViewController.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/ViewController/TransferViewController.swift
Labels: Refactor♻️, 가현💜

#26 [Refactor] #25 - 코드 수정
  KakaoPay-iOS/KakaoPay-iOS.xcodeproj/project.pbxproj
  KakaoPay-iOS/KakaoPay-iOS/Global/Extension/UIViewController+.swift
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/ic_qrscan.imageset/Contents.json
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/ic_qrscan.imageset/ic_qrscan.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/ic_qrscan.imageset/ic_qrscan@2x.png
  KakaoPay-iOS/KakaoPay-iOS/Global/Resources/Assets.xcassets/ic_qrscan.imageset/ic_qrscan@3x.png
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/AccontCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/AccountFooterView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/DirectCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/DirectFooterView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/DirectHeaderView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/MoneyHeaderView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/NewsCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/PayIssueCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/SpendingCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/TotalMoneyCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Cell/investmentAndLoanCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/Component/SectionBackgroundView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Asset/ViewController/AssetViewController.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Home/Cells/HomePayMoneyCollectionViewCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Home/View/HomeView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Home/ViewController/HomeViewController.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Payment/Model/PaymentModel.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/Cell/RecentHeaderView.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/Cell/RecentTableViewCell.swift
  KakaoPay-iOS/KakaoPay-iOS/Presentation/Transfer/View/TransferView.swift
Labels: Refactor♻️, 가현💜
